#!/usr/bin/env bash
# ===========================================================================
# Injected power-gating fault campaign for pg_top.
#
# Proves the power-aware scoreboard catches real low-power defects: a clean
# build must PASS, and each `PG_BUG_*` build must FAIL with a counterexample.
# Mirrors the SDRAM project's bug-hunt, for the isolation/retention domain.
#
# Writes bugs/BUGS.md.
# ===========================================================================
set -uo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HERE/bugs/BUGS.md"
cd "$HERE"

declare -A DESC=(
  [PG_BUG_ISO]='isolation cell removed — gated-core X drives straight into the AON domain'
  [PG_BUG_RET]='retention shadow never updated on `save` — state lost across power-down'
  [PG_BUG_SEQ]='power-off BEFORE isolate/save — retention snapshots X, which leaks on wake'
)
declare -A PROP=(
  [PG_BUG_ISO]='A — isolation'
  [PG_BUG_RET]='B — retention'
  [PG_BUG_SEQ]='A — isolation (mis-sequencing)'
)

run() {  # $1=BUG ("" = clean) ; $2=logfile ; returns check_results rc
  rm -rf sim_build results.xml
  if [ -z "$1" ]; then make >"$2" 2>&1; else make BUG="$1" >"$2" 2>&1; fi
  python3 check_results.py results.xml >>"$2" 2>&1
}

echo ">> baseline (clean RTL) ..."
run "" /tmp/pg_clean.log; clean_rc=$?

rows=""; ncaught=0; total=0
for bug in PG_BUG_ISO PG_BUG_RET PG_BUG_SEQ; do
  total=$((total+1))
  echo ">> injecting $bug ..."
  run "$bug" "/tmp/pg_${bug}.log"; rc=$?
  if [ "$rc" -ne 0 ]; then st="✅ CAUGHT"; ncaught=$((ncaught+1)); else st="❌ ESCAPED"; fi
  msg=$(grep -E 'AssertionError:' "/tmp/pg_${bug}.log" | head -1 | sed 's/.*AssertionError: //; s/[[:space:]]*$//')
  rows="${rows}| \`${bug}\` | ${DESC[$bug]} | ${PROP[$bug]} | ${st} | \`${msg:-see log}\` |\n"
done

{
  echo "# Injected power-gating fault campaign — pg_top"
  echo
  echo "> Auto-generated by \`bugs/run_bug_demo.sh\`. A clean build PASSes; each"
  echo "> \`PG_BUG_*\` build must FAIL with a counterexample (the scoreboard has teeth)."
  echo
  echo "- Baseline (clean RTL): **$( [ "$clean_rc" -eq 0 ] && echo 'PASS ✅' || echo 'FAIL ⚠ (env broken)')**"
  echo "- **Result: ${ncaught} / ${total} injected power bugs caught.**"
  echo
  echo "| Fault (\`-D\`) | What it breaks | Property violated | Outcome | Counterexample |"
  echo "|--------------|----------------|-------------------|---------|----------------|"
  printf "%b" "$rows"
  echo
  echo "## Properties (enforced every cycle by the scoreboard)"
  echo "- **A — Isolation:** \`cnt_obs\` is never X/Z; the always-on domain never"
  echo "  samples a power-gated core. (4-state Icarus makes this observable.)"
  echo "- **B — Retention:** the value the AON domain sees right after wake equals"
  echo "  the value it saw right before sleep — state survived the power cycle."
  echo "- **C — Function:** while powered & un-isolated, \`cnt_obs\` tracks the enable."
  echo
  echo "Faults are compile-time \`\`define\`\` hooks in the RTL (\`PG_BUG_*\`), so the"
  echo "clean design is byte-for-byte restored simply by not defining them."
} > "$OUT"

echo ">> ${ncaught}/${total} caught (baseline rc=$clean_rc) -> $OUT"
[ "$clean_rc" -eq 0 ] && [ "$ncaught" -eq "$total" ]
