#!/usr/bin/env bash
# ===========================================================================
# Injected-fault demonstration for the third-party AXI4-Lite crossbar env.
#
# A green scoreboard only matters if it can also go RED on a real defect.
# We inject a one-token RTL bug into the crossbar's address decoder — route
# every transaction to the WRONG slave (`m_select_next = i ^ 1`), the exact
# analogue of the SDRAM project's "wrong bank decode" bug — and prove the
# reference-model scoreboard catches it (routing / isolation check fails).
#
# The mutation is applied to the gitignored upstream clone under work/ and
# reverted with `git checkout`; upstream is never modified persistently.
#
# Writes bugs/BUGS.md.  Run AFTER ./setup.sh.
# ===========================================================================
set -uo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"     # thirdparty-dv/
VAXI="$HERE/work/verilog-axi"
TARGET="rtl/axil_crossbar_addr.v"
OUT="$HERE/bugs/BUGS.md"
[ -f "$VAXI/$TARGET" ] || { echo "ERROR: run ./setup.sh first"; exit 1; }

run_test() {  # $1=logfile ; returns 0 if all tests passed, 1 if any failed
  ( cd "$HERE" && rm -rf sim_build results.xml \
      && make MODULE=test_axil_crossbar_dv TESTCASE=directed_routing ) >"$1" 2>&1 || true
  python3 "$HERE/check_results.py" "$HERE/results.xml" >>"$1" 2>&1
}

echo ">> baseline on clean RTL ..."
git -C "$VAXI" checkout -- "$TARGET"
run_test /tmp/bugdemo_clean.log; clean_rc=$?

echo ">> injecting decode bug: m_select_next = i ^ 1 (wrong slave) ..."
sed -i 's#m_select_next = i;#m_select_next = i ^ 1; // INJECTED-BUG: route to wrong slave#' "$VAXI/$TARGET"
run_test /tmp/bugdemo_buggy.log; buggy_rc=$?

echo ">> restoring clean RTL ..."
git -C "$VAXI" checkout -- "$TARGET"

if [ "$clean_rc" -eq 0 ] && [ "$buggy_rc" -ne 0 ]; then
  verdict="✅ CAUGHT"; ok=0
else
  verdict="❌ NOT demonstrated (clean_rc=$clean_rc buggy_rc=$buggy_rc)"; ok=1
fi
errline=$(grep -E 'AssertionError:' /tmp/bugdemo_buggy.log | head -1 \
            | sed 's/.*AssertionError: //; s/^[[:space:]]*//')

{
  echo "# Injected-fault demonstration — third-party AXI4-Lite crossbar"
  echo
  echo "> Auto-generated by \`bugs/run_bug_demo.sh\`. Proves the scoreboard catches"
  echo "> a real RTL defect, not just a green light."
  echo
  echo "| Build | directed_routing | Meaning |"
  echo "|-------|------------------|---------|"
  echo "| clean upstream RTL | $( [ "$clean_rc" -eq 0 ] && echo 'PASS ✅' || echo 'FAIL ⚠' ) | env is sound on the real IP |"
  echo "| **+ injected decode bug** (\`m_select_next = i ^ 1\`) | $( [ "$buggy_rc" -ne 0 ] && echo 'FAIL ✅' || echo 'PASS ❌' ) | bug **${verdict}** |"
  echo
  echo "**Injected fault:** \`axil_crossbar_addr.v\` — \`m_select_next = i;\` →"
  echo "\`m_select_next = i ^ 1;\`, i.e. every decoded transaction is steered to the"
  echo "wrong slave port (the direct analogue of the SDRAM project's \"wrong bank"
  echo "decode\" bug)."
  echo
  echo "**Caught by:** the reference-model scoreboard — writes land in the wrong"
  echo "slave's backing memory, so both the read-back-through-the-crossbar check and"
  echo "the per-slave \`check_backing()\` (routing + isolation) assertion fire:"
  echo
  echo '```'
  echo "${errline:-<scoreboard assertion in /tmp/bugdemo_buggy.log>}"
  echo '```'
  echo
  echo "The mutation is applied only to the gitignored \`work/\` clone and reverted"
  echo "with \`git checkout\`; **upstream verilog-axi is never modified**."
} > "$OUT"

echo ">> verdict: $verdict  -> $OUT"
exit "$ok"
