#!/usr/bin/env python3
"""Parallel runner + measured-results capture for the riscv-formal checks.

Each generated SymbiYosys job (``<check>.sby``) is an independent unbounded /
bounded formal proof of one property of the core. This runs them under a
worker pool, records PASS / FAIL / ERROR / TIMEOUT and wall-time per check,
and writes:

  * ``RESULTS.md``   — grouped Markdown table + headline summary (committed)
  * ``results.json`` — machine-readable record
  * ``junit.xml``    — so CI publishes it to the run summary, exactly like
                       ``scripts/regress.py`` does for the SDRAM project.

Exit status is non-zero if *any* check did not PASS, so it gates CI.

    python3 run_checks.py --jobs $(nproc)
    python3 run_checks.py --checks-dir <dir> --only insn_ --timeout 900
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import json
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

DONE_RE = re.compile(r"DONE \((\w+), rc=(-?\d+)\)")

# prefix -> (sort key, human label) for the grouped results table
GROUPS = [
    ("insn_",    "Per-instruction ISA conformance"),
    ("reg",      "Register-file read/write consistency"),
    ("pc_fwd",   "PC forward progress"),
    ("pc_bwd",   "PC backward consistency"),
    ("liveness", "Liveness (no deadlock / forward progress)"),
    ("unique",   "Unique-state determinism"),
    ("causal",   "Causality"),
    ("csrw",     "CSR write semantics"),
    ("csrc",     "CSR counters (mcycle / minstret)"),
    ("csr_ill",  "Illegal-CSR access trapping"),
    ("cover",    "Cover (reachability liveness)"),
]
PASS = "PASS"


def classify(name: str) -> str:
    for pre, label in GROUPS:
        if name.startswith(pre):
            return label
    return "Other"


def run_one(sby: Path, timeout: int) -> dict:
    name = sby.stem
    t0 = time.time()
    status, rc, out = None, None, ""
    try:
        p = subprocess.run(
            ["sby", "-f", sby.name],
            cwd=str(sby.parent),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        out, rc = p.stdout + p.stderr, p.returncode
    except subprocess.TimeoutExpired:
        status, rc = "TIMEOUT", 124
    dt = round(time.time() - t0, 1)
    if status is None:
        m = DONE_RE.search(out)
        status = m.group(1).upper() if m else (PASS if rc == 0 else "FAIL")
    return {"name": name, "group": classify(name), "status": status,
            "seconds": dt, "rc": rc}


def write_results_md(path: Path, results: list[dict], meta: dict) -> None:
    npass = sum(r["status"] == PASS for r in results)
    total = len(results)
    by_group: dict[str, list[dict]] = {}
    for r in results:
        by_group.setdefault(r["group"], []).append(r)

    lines = [
        "# riscv-formal — measured results (PicoRV32)",
        "",
        "> Auto-generated by `run_checks.py`. Each row is one SymbiYosys formal",
        "> proof of one property of the core. **Do not edit by hand.**",
        "",
        f"- **Result: {npass} / {total} checks PASS**",
        f"- Core: PicoRV32 `{meta['picorv32_commit'][:12]}` (RV32IMC, "
        f"`sha256:{meta['picorv32_sha256'][:12]}…`)",
        f"- Harness: riscv-formal `{meta['rvf_commit'][:12]}`",
        f"- Engine: SymbiYosys + `smtbmc {meta['solver']}`  ·  "
        f"jobs={meta['jobs']}  ·  wall={meta['wall_s']}s",
        f"- Generated: {meta['utc']}",
        "",
    ]
    nonpass = [r for r in results if r["status"] != PASS]
    if nonpass:
        lines += ["## ⚠ Non-passing checks", "",
                  "| Check | Status | rc | s |", "|---|---|---|---|"]
        lines += [f"| `{r['name']}` | **{r['status']}** | {r['rc']} | {r['seconds']} |"
                  for r in nonpass]
        lines.append("")

    # one table per group, ordered as in GROUPS then any "Other"
    order = [lbl for _, lbl in GROUPS] + ["Other"]
    for group in order:
        rows = by_group.get(group)
        if not rows:
            continue
        rows.sort(key=lambda r: r["name"])
        g_pass = sum(r["status"] == PASS for r in rows)
        slow = max(r["seconds"] for r in rows)
        lines += [f"## {group} — {g_pass}/{len(rows)} pass (slowest {slow}s)", "",
                  "| Check | Status | s |", "|---|---|---|"]
        for r in rows:
            mark = "✅" if r["status"] == PASS else "❌"
            lines.append(f"| `{r['name']}` | {mark} {r['status']} | {r['seconds']} |")
        lines.append("")
    path.write_text("\n".join(lines))


def write_junit(path: Path, results: list[dict], meta: dict) -> None:
    fails = sum(r["status"] != PASS for r in results)
    secs = sum(r["seconds"] for r in results)
    out = [f'<testsuite name="riscv-formal.picorv32" tests="{len(results)}" '
           f'failures="{fails}" time="{secs:.1f}">']
    for r in results:
        out.append(f'  <testcase classname="{escape(r["group"])}" '
                   f'name="{escape(r["name"])}" time="{r["seconds"]:.1f}">')
        if r["status"] != PASS:
            out.append(f'    <failure message="{r["status"]} rc={r["rc"]}"/>')
        out.append("  </testcase>")
    out.append("</testsuite>")
    path.write_text("\n".join(out))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    here = Path(__file__).resolve().parent
    ap.add_argument("--checks-dir", default=str(
        here / "work/riscv-formal/cores/picorv32/checks"),
        help="directory containing the generated *.sby checks")
    ap.add_argument("--jobs", type=int, default=4, help="parallel sby workers")
    ap.add_argument("--timeout", type=int, default=1800,
                    help="per-check wall-clock timeout (s)")
    ap.add_argument("--only", default="",
                    help="only run checks whose name starts with one of these "
                         "comma-separated prefixes (e.g. insn_add,reg,pc_fwd)")
    ap.add_argument("--out", default=str(here / "results"),
                    help="output directory for RESULTS.md / json / junit")
    args = ap.parse_args()

    cdir = Path(args.checks_dir)
    prefixes = tuple(x for x in args.only.split(",") if x)
    sbys = sorted(p for p in cdir.glob("*.sby")
                  if not prefixes or p.stem.startswith(prefixes))
    if not sbys:
        print(f"no checks found in {cdir} (run ./setup.sh first?)", file=sys.stderr)
        return 2

    # pull the pinned revisions back out of setup.sh so RESULTS.md is self-describing
    setup = (here / "setup.sh").read_text()
    def grab(key, default="?"):
        m = re.search(rf"^{key}=(\S+)", setup, re.M)
        return m.group(1) if m else default
    solver = "?"
    cfg = cdir.parent / "checks.cfg"
    if cfg.exists():
        m = re.search(r"^solver (\S+)", cfg.read_text(), re.M)
        solver = m.group(1) if m else "?"

    print(f">> {len(sbys)} checks · {args.jobs} jobs · solver={solver} · "
          f"timeout={args.timeout}s")
    t0 = time.time()
    results: list[dict] = []
    with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        futs = {ex.submit(run_one, s, args.timeout): s for s in sbys}
        for i, fut in enumerate(cf.as_completed(futs), 1):
            r = fut.result()
            results.append(r)
            mark = "ok " if r["status"] == PASS else "XXX"
            print(f"  [{i:>2}/{len(sbys)}] {mark} {r['name']:<28} "
                  f"{r['status']:<8} {r['seconds']:>6.1f}s")
    wall = round(time.time() - t0, 1)
    results.sort(key=lambda r: r["name"])

    meta = {
        "rvf_commit": grab("RVF_COMMIT"),
        "picorv32_commit": grab("PICORV32_COMMIT"),
        "picorv32_sha256": grab("PICORV32_SHA256"),
        "solver": solver,
        "jobs": args.jobs,
        "wall_s": wall,
        "utc": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ"),
    }
    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)
    write_results_md(outdir / "RESULTS.md", results, meta)
    write_junit(outdir / "junit.xml", results, meta)
    (outdir / "results.json").write_text(json.dumps(
        {"meta": meta, "checks": results}, indent=2))

    npass = sum(r["status"] == PASS for r in results)
    print(f">> {npass}/{len(results)} PASS in {wall}s wall  "
          f"-> {outdir/'RESULTS.md'}")
    return 0 if npass == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
