#!/usr/bin/env bash
# ===========================================================================
# Injected-fault demonstration for the riscv-formal / PicoRV32 flow.
#
# A green proof run only means something if the same environment can also go
# RED on a real defect. PicoRV32 ships five one-token fault hooks
# (`PICORV32_TESTBUG_001..005`). For each, we switch the hook on, regenerate
# the checks for that faulty build, and run the single check that should catch
# it — expecting the proof to FAIL with a counterexample trace.
#
# Writes the measured table to bugs/BUGS.md.  Run AFTER ./setup.sh.
# ===========================================================================
set -uo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"            # riscv-formal/
CORE="$HERE/work/riscv-formal/cores/picorv32"
OUT="$HERE/bugs/BUGS.md"
[ -d "$CORE/checks" ] || { echo "ERROR: run ./setup.sh first"; exit 1; }
cd "$CORE"

# bug -> the check expected to catch it (chosen to be fast + unambiguous)
declare -A CHECK=(
  [001]=reg_ch0  [002]=reg_ch0  [003]=insn_addi_ch0  [004]=insn_addi_ch0  [005]=pc_fwd_ch0 )
declare -A FAULT=(
  [001]='writeback to the WRONG register: cpuregs[latched_rd ^ 1] <= wrdata'
  [002]='writeback the WRONG data: cpuregs[latched_rd] <= wrdata ^ 1'
  [003]='RVFI reports the WRONG rd_addr: rvfi_rd_addr <= latched_rd ^ 1'
  [004]='RVFI reports the WRONG rd_wdata: rvfi_rd_wdata <= ... ^ 1'
  [005]='RVFI reports the WRONG next-PC: rvfi_pc_wdata = ... ^ 4' )
declare -A CLASS=(
  [001]='functional (register file)' [002]='functional (register file)'
  [003]='trace / decode' [004]='trace / data' [005]='control-flow' )

rows=""; ncaught=0; total=0
for bug in 001 002 003 004 005; do
  total=$((total+1)); chk=${CHECK[$bug]}
  sed "s/PICORV32_TESTBUG_NONE/PICORV32_TESTBUG_${bug}/" checks.cfg > "testbug${bug}.cfg"
  python3 ../../checks/genchecks.py "testbug${bug}" >/dev/null 2>&1
  rm -rf "testbug${bug}/${chk}"
  start=$(date +%s)
  ( cd "testbug${bug}" && sby -f "${chk}.sby" ) >"/tmp/tb_${bug}.log" 2>&1
  end=$(date +%s)
  res=$(grep -oE 'DONE \([A-Z]+' "/tmp/tb_${bug}.log" | tail -1 | grep -oE '[A-Z]+$')
  if [ "$res" = "FAIL" ]; then
    status="✅ CAUGHT"; ncaught=$((ncaught+1))
    trace="testbug${bug}/${chk}/engine_0/trace.vcd"
    [ -f "$CORE/$trace" ] && tnote="\`$trace\`" || tnote="(counterexample produced)"
  else
    status="❌ ESCAPED"; tnote="proof still PASSed — fault not caught!"
  fi
  printf '  TB%s  %-15s  %-11s  %ss\n' "$bug" "$chk" "$status" "$((end-start))"
  rows="${rows}| TB${bug} | ${FAULT[$bug]} | ${CLASS[$bug]} | \`${chk}\` | ${status} | $((end-start))s |\n"
done

{
  echo "# Injected-fault demonstration — riscv-formal / PicoRV32"
  echo
  echo "> Auto-generated by \`bugs/run_bug_demo.sh\`. Each row activates one of"
  echo "> PicoRV32's \`PICORV32_TESTBUG_*\` hooks and runs the check that should"
  echo "> catch it; **CAUGHT** means the formal proof failed with a counterexample"
  echo "> (the desired outcome — the suite has teeth)."
  echo
  echo "**Result: ${ncaught} / ${total} injected faults caught.**"
  echo
  echo "| Bug | Injected fault (1-token mutation) | Class | Catching check | Outcome | Wall |"
  echo "|-----|-----------------------------------|-------|----------------|---------|------|"
  printf "%b" "$rows"
  echo
  echo "## Why these checks catch these faults"
  echo
  echo "- **TB001/002** corrupt the *actual* register write while RVFI keeps"
  echo "  reporting the intended address/value, so the architectural register"
  echo "  diverges from RVFI's claim — the \`reg\` consistency proof (compare what"
  echo "  RVFI says was written to \`xN\` against what is later read) fails."
  echo "- **TB003/004** corrupt the RVFI *trace* (\`rd_addr\`/\`rd_wdata\`); every"
  echo "  per-instruction check compares the trace against the decoded ISA"
  echo "  expectation, so e.g. \`insn_addi\` fails immediately."
  echo "- **TB005** corrupts the reported next-PC; the \`pc_fwd\` forward-progress"
  echo "  proof (and the per-instruction next-PC check) fails."
  echo
  echo "Each counterexample is a concrete VCD trace under the matching"
  echo "\`work/.../picorv32/testbugNNN/<check>/engine_0/\` directory; disassemble"
  echo "the offending instruction with the core's \`disasm.py\` if desired."
} > "$OUT"

echo ">> ${ncaught}/${total} caught -> $OUT"
[ "$ncaught" -eq "$total" ]
